version: '3.7'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.1
    deploy:
       mode: replicated
       replicas: 1
       restart_policy:
         condition: on-failure
         delay: 20s
         max_attempts: 3
         window: 30s
       update_config:
         parallelism: 1
         delay: 40s
         failure_action: rollback
         order: start-first
    volumes:
    - "./conf/:/usr/share/logstash/conf/"
    - "./pipeline/:/usr/share/logstash/pipeline/"
